export const opholdData = [
  {
    image: "../src/_images/1.jpg",
    title: "Maldiverne, Sri Lanka, Bali & Gili Islands",
    subtitle: "For dig der elsker sol, sommer og højt humør",
    countrues: "Maldiverne, Sri Lanka, Bali & Gili Islands",
    dato: "10/09/2022",
    afrejse: "Efterår",
    pris: "fra 43.900 kr.",
    undervisning: "Selvudvikling og kommunikation",
    varig: "2 Måneder",
  },
  {
    image: "../src/_images/1.jpg",
    title: "Bali, Lombok & Gili Islands",
    subtitle: "For dig der elsker sol, sommer og højt humør",
    countrues: "Bali, Lombok & Gili Islands",
    dato: "06/07/2022",
    afrejse: "Sommer",
    pris: "fra 28.400 kr.",
    undervisning: "Selvudvikling og kommunikation",
    varig: "1 Måneder",
  },
  {
    image: "../src/_images/1.jpg",
    title: "Caribien, Hawaii & Mexico",
    subtitle: "For dig der elsker sol, sommer og højt humør",
<<<<<<< HEAD
    countrues: "Sri Lanka Maldiverne & Thailand",
    dato: "14/22/2022",
    afrejse: "Til månen",
    pris: "fra 59.700 kr.",
=======
    countrues: "Caribien, Hawaii & Mexico",
    dato: "01/12/2022",
    afrejse: "Efterår",
    pris: "fra 59.500 kr.",
>>>>>>> dabe26205c6215ab0a45bccc311c03fb1bd9fda8
    undervisning: "Selvudvikling og kommunikation",
    varig: "3 Måneder",
  },
  {
    image: "../src/_images/1.jpg",
    title: "Costa Rica, Mexico & Guatemala",
    subtitle: "For dig der elsker sol, sommer og højt humør",
    countrues: "Costa Rica, Mexico & Guatemala",
    dato: "14/22/2022",
    afrejse: "Forår",
    pris: "fra 49.900 kr.",
    undervisning: "Selvudvikling og kommunikation",
    varig: "3 Måneder",
  },
  {
    image: "../src/_images/1.jpg",
    title: "Indien, Nepal, Thailand & Sri Lanka",
    subtitle: "For dig der elsker sol, sommer og højt humør",
    countrues: "Indien, Nepal, Thailand & Sri Lanka",
    dato: "14/02/2023",
    afrejse: "Forår",
    pris: "fra 48.900 kr.",
    undervisning: "Selvudvikling og kommunikation",
    varig: "3 Måneder",
  },
  {
    image: "../src/_images/1.jpg",
    title: "Hawaii, Australien, Japan, Bali & Gili Islands",
    subtitle: "For dig der elsker sol, sommer og højt humør",
    countrues: "Hawaii, Australien, Japan, Bali & Gili Islands",
    dato: "25/01/2023",
    afrejse: "forår",
    pris: "fra 76.900 kr.",
    undervisning: "Selvudvikling og kommunikation",
    varig: "1 Måneder",
  },
];
